### ISSUE TITLE
Not using `<!--break-->` in a blog post throws unhelpful error

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#632]
It throws because `content` is empty as the whole blog post is considered as excerpt. 

We should throw in `splitPostContent` if the length of the resulting array !== 2.

```
ERROR Summary:
  - broccoliBuilderErrorStack: TypeError: Cannot read property 'replace' of undefined
    at encodeCurlies (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:154:18)
    at htmlizeBody (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:170:10)
    at ComponentsBuilder._preparePostTemplateData (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:121:13)
    at ComponentsBuilder._writeStartPageComponent (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:60:20)
    at ComponentsBuilder.writeComponentFiles (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:40:10)
    at ComponentsBuilder.build (/home/travis/build/simplabs/simplabs.github.io/lib/component-generation/base-components-builder.js:24:10)
    at /home/travis/build/simplabs/simplabs.github.io/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/travis/build/simplabs/simplabs.github.io/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/travis/build/simplabs/simplabs.github.io/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/travis/build/simplabs/simplabs.github.io/node_modules/rsvp/dist/rsvp.js:508:7)
  - code: [undefined]
  - codeFrame: Cannot read property 'replace' of undefined
  - errorMessage: Cannot read property 'replace' of undefined
        at ComponentsBuilder
-~- created here: -~-
    at ComponentsBuilder.Plugin (/home/travis/build/simplabs/simplabs.github.io/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/home/travis/build/simplabs/simplabs.github.io/node_modules/broccoli-caching-writer/index.js:18:10)
    at new BaseComponentsBuilder (/home/travis/build/simplabs/simplabs.github.io/lib/component-generation/base-components-builder.js:13:5)
    at new ComponentsBuilder (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/lib/components-builder.js:23:18)
    at Class.preprocessTree (/home/travis/build/simplabs/simplabs.github.io/lib/generate-blog/index.js:22:27)
    at /home/travis/build/simplabs/simplabs.github.io/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:10:25
    at Array.reduce (<anonymous>)
    at Object.addonProcessTree (/home/travis/build/simplabs/simplabs.github.io/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:8:32)
    at SimplabsApp.buildTrees (/home/travis/build/simplabs/simplabs.github.io/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:115:47)
    at new GlimmerApp (/home/travis/build/simplabs/simplabs.github.io/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:52:27)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
```

**Comment by marcoow** [comment]
Good catch - I think we should assert that `<!--break-->` appears in the post's source.
